### PR TITLE
feat/add-ttlcache-support

### PR DESCRIPTION
**Pull request by Sadzurami**
Would be nice to see ttlcache in this lib, i think it would be useful in future.

### CODE REVIEW

**Comment by Gobot1234** [comment]
I've been talking with McKay about this and was just curious if there's any reason this isn't generic over its key and or value type?

**Comment by Sadzurami** [comment]
> I've been talking with McKay about this and was just curious if there's any reason this isn't generic over its key and or value type?

Nope, it's possible to make generics.

I'm waiting McKay's response, and if required, i can make changes.

**Comment by DoctorMcKay** [comment]
A generic for the value could be useful, but keeping the key as string makes most sense to me.

**Comment by Sadzurami** [comment]
Looks like, only way to add generics to only values - make generics on `add` and `get` methods, not for class itself.

Typing updated.

**Comment by DoctorMcKay** [comment]
I don't really care for generics on those methods, could get annoying fast. I want to make some tweaks anyway so I'll just merge this and remove the generics.

**Pull request merged**
